spring:
    datasource:
        url: jdbc:p6spy:h2:file:./db
        platform: h2
        username: sa
        password:
        driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: true
                format_sql: true
        generate-ddl: false

    h2:
        console:
            enabled: true
            path: /console
            settings:
                trace: false
                web-allow-others: false
